-keep class com.btech.presentation.*.** {*;}
-keep class com.btech.presentation.theme.*.** {*;}
-keep class com.btech.presentation.theme.BtechColors.** {*;}
-keep class com.btech.presentation.theme.BtechColors {*;}
-keep class com.btech.presentation.theme.BtechTheme {*;}
-keep class com.btech.presentation.theme.BtechTheme.*.** {*;}
-dontwarn java.lang.invoke.StringConcatFactory